---
  - name: Install mariadb-server python-mysqldb in controller node
    apt: name={{ item }} state=present force=yes
    with_items:
     - mariadb-server
     - python-mysqldb
  - name: Changing my.cnf file
    template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  - name: Copy python script to change the root password
    copy: src=../../change_mysql_root_password.py dest=/var/tmp/change_mysql_root_password.py owner=root group=root mode=755
  - name: Change root user password
    command: /usr/bin/python /var/tmp/change_mysql_root_password.py "{{ mysql_root_password }}"
##    notify:
##     - Restart MySQL
  - name: Restart MySQL
    service: name=mysql state=restarted
