---
  - name: Install rabbitmq-server in controller node
    apt: name=rabbitmq-server state=present force=yes
  - name: Change password for guest user of rabbitMQ
    command: rabbitmqctl change_password guest {{ rabbit_pass }}
#    rabbitmq_user: user=guest password= {{ rabbit_pass }}
  - name: Configure rabbitmq.config
    template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
##  - name: Set privilege for guest user
##    command: rabbitmqctl set_permissions guest ".*" ".*" ".*"
##    notify:
##     - Restart RabbitMQ
  - name: Restart RabbitMQ
    service: name=rabbitmq-server state=restarted
