---
- name: Restart Neutron-plugin-openvswitch-agent
  service: name=neutron-plugin-openvswitch-agent state=restarted
- name: Restart Neutron-l3-agent
  service: name=neutron-l3-agent state=restarted
- name: Restart Neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=restarted
- name: Restart Neutron-metadata-agent
  service: name=neutron-metadata-agent state=restarted
